let mongoose = require("mongoose");

let blogSchema = mongoose.Schema({
  title: { type: String, required: true },
  blogURL: { type: String, required: true, unique: true },
  shortDes: { type: String, required: true },
  longDesFirst: { type: String, required: true },
  longDesMiddle1: { type: String },
  longDesMiddle2: { type: String },
  longDesMiddle3: { type: String },
  longDesMiddle4: { type: String },
  longDesMiddle5: { type: String },
  longDesMiddle6: { type: String },
  longDesMiddle7: { type: String },
  longDesMiddle8: { type: String },
  longDesMiddle9: { type: String },
  longDesMiddle10: { type: String },
  longDesLast: { type: String },
  img: { type: String, required: true },
  imgGrid1: { type: String },
  imgGrid2: { type: String },
  imgGrid3: { type: String },
  imgGrid4: { type: String },
  imgGrid5: { type: String },
  imgGrid6: { type: String },
  imgGrid7: { type: String },
  imgGrid8: { type: String },
  imgGrid9: { type: String },
  imgGrid10: { type: String },
  amazonLink1: { type: String },
  amazonLink2: { type: String },
  amazonLink3: { type: String },
  amazonLink4: { type: String },
  amazonLink5: { type: String },
  amazonLink6: { type: String },
  amazonLink7: { type: String },
  amazonLink8: { type: String },
  amazonLink9: { type: String },
  amazonLink10: { type: String },
  pros1: { type: Array },
  cons1: { type: Array },
  pros2: { type: Array },
  cons2: { type: Array },
  pros3: { type: Array },
  cons3: { type: Array },
  pros4: { type: Array },
  cons4: { type: Array },
  pros5: { type: Array },
  cons5: { type: Array },
  pros6: { type: Array },
  cons6: { type: Array },
  pros7: { type: Array },
  cons7: { type: Array },
  pros8: { type: Array },
  cons8: { type: Array },
  pros9: { type: Array },
  cons9: { type: Array },
  pros10: { type: Array },
  cons10: { type: Array },
  buttonTxt: { type: String },
  imgAlt: { type: String, required: true },
  author: { type: String, required: true },
  views: { type: Number },
  metaTitle: { type: String, required: true },
  metaDes: { type: String, required: true },
  metaKeywords: { type: String, required: true },
  storeId: { type: String },
  relatedStores: { type: Array },
  showVertically: { type: Boolean, required: true },
  featuredForHome: { type: Boolean, required: true },
  CreatedAt: { type: String, default: Date.now() },
});

module.exports = mongoose.model("Blog", blogSchema);
