const { ObjectID } = require('mongodb');
let mongoose = require('mongoose');

let blogSchema = mongoose.Schema({
    title: { type: String, required: true },
    blogURL: { type: String, required: true, unique: true },
    shortDes: { type: String, required: true },
    longDesFirst: { type: String, required: true },
    longDesMiddle1: { type: String },
    longDesMiddle2: { type: String },
    longDesMiddle3: { type: String },
    longDesMiddle4: { type: String },
    longDesMiddle5: { type: String },
    longDesMiddle6: { type: String },
    longDesMiddle7: { type: String },
    longDesMiddle8: { type: String },
    longDesMiddle9: { type: String },
    longDesMiddle10: { type: String },
    longDesLast: { type: String },
    framestartContent: {
        type: String,
        ref: 'gridProduct'
    },
    frameMiddle1: { type: String, ref: 'gridProduct' },
    frameMiddle2: { type: String, ref: 'gridProduct' },
    frameMiddle3: { type: String, ref: 'gridProduct' },
    frameMiddle4: { type: String, ref: 'gridProduct' },
    frameMiddle5: { type: String, ref: 'gridProduct' },
    frameMiddle6: { type: String, ref: 'gridProduct' },
    frameMiddle7: { type: String, ref: 'gridProduct' },
    frameMiddle8: { type: String, ref: 'gridProduct' },
    frameMiddle9: { type: String, ref: 'gridProduct' },
    frameMiddle10: { type: String, ref: 'gridProduct' },
    img: { type: String, required: true },
    imgGrid1: { type: String },
    imgGrid2: { type: String },
    imgGrid3: { type: String },
    imgGrid4: { type: String },
    imgGrid5: { type: String },
    imgGrid6: { type: String },
    imgGrid7: { type: String },
    imgGrid8: { type: String },
    imgGrid9: { type: String },
    imgGrid10: { type: String },
    amazonLink1: { type: String },
    amazonLink2: { type: String },
    amazonLink3: { type: String },
    amazonLink4: { type: String },
    amazonLink5: { type: String },
    amazonLink6: { type: String },
    amazonLink7: { type: String },
    amazonLink8: { type: String },
    amazonLink9: { type: String },
    amazonLink10: { type: String },
    buttonTxt: { type: String, required: true },
    imgAlt: { type: String, required: true },
    author: { type: String, required: true },
    views: { type: Number },
    metaTitle: { type: String, required: true },
    metaDes: { type: String, required: true },
    metaKeywords: { type: String, required: true },
    storeId: { type: String, required: true },
    relatedStores: { type: Array },
    showVertically: { type: Boolean, required: true },
    featuredForHome: { type: Boolean, required: true },
    amazonAdsAdded: { type: Boolean, required: true },
    CreatedAt: { type: String, default: Date.now() }
});

module.exports = mongoose.model('Blog', blogSchema);